### ISSUE TITLE
URL for zip file points to OER instead of Course Hub

### ISSUE THREAD

**Issue by floatingtim** [hibbitts-design/hibbitts-design-org-learn#1]
[http://hibbittsdesign.org/blog/downloads/grav-skeleton-course-hub-site.zip](http://hibbittsdesign.org/blog/downloads/grav-skeleton-course-hub-site.zip)

instead of 

[http://hibbittsdesign.org/blog/downloads/grav-skeleton-course-hub-site.zip](http://hibbittsdesign.org/blog/downloads/grav-skeleton-oer-content-space-site.zip)

**Comment by paulhibbitts** [comment]
Thanks so much for catching that! The link has now been corrected on http://learn.hibbittsdesign.org/coursehub/getting-ready
